In [44]:
import pandas as pd
import numpy as np

import statsmodels.api as sm
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split, cross_val_score

In [2]:
data = pd.read_csv('data.csv')
data=data.iloc[:,1:]
data.head()

TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [3]:
X = data.drop('Sales', axis=1)
y = data['Sales']

In [4]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [6]:
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [9]:
# Statsmodels
modelStas = sm.OLS(y, X).fit()

In [10]:
modelStas.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  Sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Mon, 09 Sep 2024   Prob (F-statistic):                   2.43e-171
Time:                        20:19:54   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
Radio          0.2222      0.009     23.595      0.000       0.204       0.241
Newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [12]:
modelScikit = LinearRegression()
modelScikit.fit(X, y)

LinearRegression()

In [13]:
modelScikit.coef_

array([ 0.04576465,  0.18853002, -0.00103749])

In [14]:
modelScikit.intercept_

2.938889369459412

## PREDİCT

In [15]:
# Sales = 7.032594 + 0.047537*TV + 0.188530*Radio - 0.001037*Newspaper

In [16]:
# 30 birim TV, 10 birim Radio, 40 birim Newspaper
7.032594 + 0.047537*30 + 0.188530*10 - 0.001037*40

10.302523999999998

In [19]:
seri = pd.DataFrame([[30],[10],[40]])
seri = seri.T
seri

0   1   2
0  30  10  40

In [20]:
modelScikit.predict(seri)

c:\Users\polat\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([6.15562918])

In [22]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [23]:
modelScikit.predict(X)[:10]

array([20.52397441, 12.33785482, 12.30767078, 17.59782951, 13.18867186,
       12.47834763, 11.72975995, 12.12295317,  3.72734086, 12.55084872])

In [26]:
MSE =mean_squared_error(y, modelScikit.predict(X))
MSE

2.784126314510936

In [28]:
RMSE = mean_squared_error(y, modelScikit.predict(X))**0.5
RMSE

1.6685701407225697

## MODEL TUNİNG

In [31]:
X.head()

TV  Radio  Newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [32]:
y.head()

0    22.1
1    10.4
2     9.3
3    18.5
4    12.9
Name: Sales, dtype: float64

In [33]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [34]:
X_train.head()

TV  Radio  Newspaper
79   116.0    7.7       23.1
197  177.0    9.3        6.4
38    43.1   26.7       35.1
24    62.3   12.6       18.3
122  224.0    2.4       15.6

In [36]:
y_train.head()

79     11.0
197    12.8
38     10.1
24      9.7
122    11.6
Name: Sales, dtype: float64

In [37]:
modelScikit.fit(X_train, y_train)

LinearRegression()

In [39]:
# Eğitim Hatası
RMSE = mean_squared_error(y_train, modelScikit.predict(X_train))**0.5
RMSE

1.644727765644337

In [40]:
# Test Hatası
RMSE = mean_squared_error(y_test, modelScikit.predict(X_test))**0.5
RMSE

1.78159966153345

In [42]:
# K-Katlı CV :
cross_val_score(modelScikit, X, y, cv=10, scoring='neg_mean_squared_error')

array([-3.56038438, -3.29767522, -2.08943356, -2.82474283, -1.3027754 ,
       -1.74163618, -8.17338214, -2.11409746, -3.04273109, -2.45281793])

In [45]:
np.mean(-cross_val_score(modelScikit, X, y, cv=10, scoring='neg_mean_squared_error'))**0.5

1.749276312684338